/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Charm.gltf --transform
Author: vattghernca (https://sketchfab.com/vattghernca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hw-xyz-school-detailing-chameleon-f155233640474b2d9ba86cc671305284
Title: [HW XYZ School] Detailing: Chameleon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Charm-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 8.68, -0.41]} scale={[3.27, 4.81, 8.48]}>
          <group position={[0, -0.03, 0]}>
            <group position={[0, 0.01, 0]} scale={[0.93, 1, 1]}>
              <mesh geometry={nodes.polySurface69_blue_01_0.geometry} material={materials.blue_01} />
              <mesh geometry={nodes.polySurface69_blue_02_0.geometry} material={materials.blue_02} />
            </group>
            <mesh geometry={nodes.polySurface54_blue_01_0.geometry} material={materials.blue_01} />
          </group>
          <mesh geometry={nodes.polySurface114_blue_01_0.geometry} material={materials.blue_01} />
          <mesh geometry={nodes.polySurface114_blue_02_0.geometry} material={materials.blue_02} />
          <mesh geometry={nodes.polySurface115_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface35_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface35_white_02_0.geometry} material={materials.white_02} />
          <mesh geometry={nodes.polySurface35_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface35_dark_braun_0.geometry} material={materials.dark_braun} />
        </group>
        <group position={[0, 6.89, -6.13]}>
          <group position={[0, 0, 0.33]} scale={[1.31, 1, 1]}>
            <mesh geometry={nodes.polySurface373_blue_02_0.geometry} material={materials.blue_02} />
            <mesh geometry={nodes.polySurface373_blue_01_0.geometry} material={materials.blue_01} />
            <mesh geometry={nodes.polySurface374_red_02_0.geometry} material={materials.red_02} />
            <mesh geometry={nodes.polySurface374_red_0.geometry} material={materials.material} />
          </group>
        </group>
        <group position={[0, -0.07, 0]}>
          <mesh geometry={nodes.polySurface333_black_0.geometry} material={materials.black} />
          <mesh geometry={nodes.polySurface385_black_0.geometry} material={materials.black} />
        </group>
        <group position={[0, 0.46, 0]}>
          <mesh geometry={nodes.polySurface187_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface188_white_02_0.geometry} material={materials.white_02} />
          <mesh geometry={nodes.polySurface189_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface189_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface190_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface191_white_02_0.geometry} material={materials.white_02} />
          <mesh geometry={nodes.polySurface191_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface192_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface192_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface193_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface194_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface195_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface196_light_0.geometry} material={materials.light} />
          <mesh geometry={nodes.polySurface197_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface198_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface199_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface200_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface201_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface201_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface202_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.polySurface203_braun_0.geometry} material={materials.braun} />
        </group>
        <group position={[-2.27, 11.11, 1.12]} rotation={[0.09, Math.PI / 2, 0]} scale={0.63}>
          <mesh geometry={nodes.polySurface211_white_02_0.geometry} material={materials.white_02} />
          <mesh geometry={nodes.polySurface211_white_01_0.geometry} material={materials.white_01} />
          <mesh geometry={nodes.polySurface212_braun_0.geometry} material={materials.braun} />
          <mesh geometry={nodes.polySurface213_braun_0.geometry} material={materials.braun} />
        </group>
        <group position={[0, 1.36, 0.48]} scale={0.87}>
          <mesh geometry={nodes.polySurface386_light_light_blu_0.geometry} material={materials.light_light_blu} />
          <mesh geometry={nodes.polySurface386_dark_light_0.geometry} material={materials.dark_light} />
          <mesh geometry={nodes.polySurface386_blue_01_0.geometry} material={materials.blue_01} />
          <mesh geometry={nodes.polySurface386_blue_02_0.geometry} material={materials.blue_02} />
          <mesh geometry={nodes.polySurface386_light_gold_0.geometry} material={materials.light_gold} />
          <mesh geometry={nodes.polySurface386_dark_gold_0.geometry} material={materials.dark_gold} />
        </group>
        <group position={[0.02, 0, 0]}>
          <mesh geometry={nodes.polySurface398_light_gold_0.geometry} material={materials.light_gold} />
          <mesh geometry={nodes.polySurface398_dark_gold_0.geometry} material={materials.dark_gold} />
          <mesh geometry={nodes.polySurface398_red_02_0.geometry} material={materials.red_02} />
          <mesh geometry={nodes.polySurface398_red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.polySurface398_blue_02_0.geometry} material={materials.blue_02} />
          <mesh geometry={nodes.polySurface398_light_light_blu_0.geometry} material={materials.light_light_blu} />
        </group>
        <mesh geometry={nodes.pCylinder1_white_02_0.geometry} material={materials.white_02} position={[-0.15, 0.2, 0]} />
        <mesh geometry={nodes.pCylinder2_dark_gold_0.geometry} material={materials.dark_gold} position={[0, 0.25, 0]} />
        <mesh geometry={nodes.pCylinder3_white_01_0.geometry} material={materials.white_01} position={[0.16, 0.14, 0]} />
        <mesh geometry={nodes.pCylinder6_white_01_0.geometry} material={materials.white_01} />
        <mesh geometry={nodes.pCylinder7_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.polySurface57_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.pCube40_blue_02_0.geometry} material={materials.blue_02} />
        <mesh geometry={nodes.pCylinder18_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface62_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.polySurface62_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.pGear4_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.pGear4_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.pGear5_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.pGear5_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.polySurface64_dark_braun_0.geometry} material={materials.dark_braun} />
        <mesh geometry={nodes.polySurface64_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.polySurface70_dark_braun_0.geometry} material={materials.dark_braun} />
        <mesh geometry={nodes.polySurface70_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.polySurface336_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.polySurface337_white_01_0.geometry} material={materials.white_01} />
        <mesh geometry={nodes.polySurface337_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.polySurface338_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.polySurface339_white_01_0.geometry} material={materials.white_01} />
        <mesh geometry={nodes.polySurface339_braun_0.geometry} material={materials.braun} />
        <mesh geometry={nodes.pCube43_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.pCylinder34_white_01_0.geometry} material={materials.white_01} />
        <mesh geometry={nodes.pCylinder35_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pCube50_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.pCube51_red_02_0.geometry} material={materials.red_02} />
        <mesh geometry={nodes.pCube51_red_0.geometry} material={materials.material} />
        <mesh geometry={nodes.polySurface380_blue_01_0.geometry} material={materials.blue_01} />
        <mesh geometry={nodes.polySurface380_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface380_blue_02_0.geometry} material={materials.blue_02} />
        <mesh geometry={nodes.polySurface364_red_02_0.geometry} material={materials.red_02} />
        <mesh geometry={nodes.polySurface364_red_0.geometry} material={materials.material} />
        <mesh geometry={nodes.polySurface278_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.polySurface278_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface278_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface278_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.polySurface278_light_light_blu_0.geometry} material={materials.light_light_blu} />
        <mesh geometry={nodes.polySurface278_dark_light_0.geometry} material={materials.dark_light} />
        <mesh geometry={nodes.polySurface278_white_01_0.geometry} material={materials.white_01} />
        <mesh geometry={nodes.polySurface278_white_02_0.geometry} material={materials.white_02} />
        <mesh geometry={nodes.polySurface330_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.polySurface330_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.polySurface330_blue_02_0.geometry} material={materials.blue_02} />
        <mesh geometry={nodes.polySurface330_blue_01_0.geometry} material={materials.blue_01} />
        <mesh geometry={nodes.polySurface330_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface330_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface330_light_light_blu_0.geometry} material={materials.light_light_blu} />
        <mesh geometry={nodes.polySurface330_dark_light_0.geometry} material={materials.dark_light} />
        <mesh geometry={nodes.polySurface352_dark_gold_0.geometry} material={materials.dark_gold} />
        <mesh geometry={nodes.polySurface352_light_gold_0.geometry} material={materials.light_gold} />
        <mesh geometry={nodes.polySurface352_blue_02_0.geometry} material={materials.blue_02} />
        <mesh geometry={nodes.polySurface352_blue_01_0.geometry} material={materials.blue_01} />
        <mesh geometry={nodes.polySurface352_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface352_lambert16_0.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.polySurface352_light_light_blu_0.geometry} material={materials.light_light_blu} />
        <mesh geometry={nodes.polySurface352_dark_light_0.geometry} material={materials.dark_light} />
        <mesh geometry={nodes.pCylinder48_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.pCylinder49_black_0.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Charm-transformed.glb')
